name: Publish VS Code Extension

on:
  push:
    branches:
      - main  # or the name of your default branch
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Install VSCE
      run: npm install --global vsce

    - name: Run Lint
      run: npm run lint

    - name: Run Tests
      run: xvfb-run -a npm test

    - name: Package Extension
      run: vsce package