# find docs on CI for VS Code extensions here: https://code.visualstudio.com/api/working-with-extensions/continuous-integration
name: Build, Test, and Lint

on:
  push:
    branches:
      - main  # or the name of your default branch
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Install VSCE
      run: npm install --global vsce

    - name: Run Lint
      run: npm run lint

    - name: Run Headless Tests
      run: xvfb-run -a npm test

    - name: Package Extension
      run: vsce package